<a href="https://colab.research.google.com/github/FrankHolzkamp/FundamentalsActiveInference/blob/main/Probability_Models_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

rng = np.random.default_rng(42)

In [37]:
print(rng.random())
print(rng.random(5))
print(rng.random([3,3]))

0.7739560485559633
[0.43887844 0.85859792 0.69736803 0.09417735 0.97562235]
[[0.7611397  0.78606431 0.12811363]
 [0.45038594 0.37079802 0.92676499]
 [0.64386512 0.82276161 0.4434142 ]]


In [59]:
# Generate a Binomial(50,0.2) random variable
def binomial(n,p):
  U=rng.random(n)
  return sum(U < p)

print(binomial(50,0.5))

28


In [77]:
# random choice from array
def X ():
  A = [0.35 ,0.5 ,0.9 ,1]
  x = [1 ,2 ,3 ,4]
  j = 0
  U = rng . random ()
  while U > A [ j ]:
    j = j + 1
    return x [ j ]

In [88]:
print(X())
# identisch mit
print(rng.choice([1,2,3,4],p=[0.35,0.15,0.4,0.1]))

None
1
